language: ruby
rvm:
  - ruby-head
bundler_args: --without development
before_install:
  - gem install bundler --pre
  
before_script:
  - psql -c 'create database community_test;' -U postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
